### ISSUE TITLE
NUC can't boot with just HDMI connected.

### ISSUE THREAD

**Issue by ghost** [alexpotter1/intel-nuc6i7kyk-opencore#1] opened 2020-04-22 13:57 UTC
Monitor: 
I can't get HDMI to work (don't have DP to test) but just having HDMI plugged in will start the boot process and at the stage where you would expect the Apple Logo the screen just turns black and the NUC reset itself. For now I have unplugged HDMI and using USB-C / Thunderbolt and that seems to work fine. Any idea how to get just HDMI to work?

Boot / Volumes:
Just FYI - I have replaced VBoxHfs.efi with HfsPlus.efi so OpenCore can see and boot my APFS Fusion Drive. (I've got two exactly the same Crucial M2 SSD installed)

Thanks a lot for your work, pretty straight forward process with awesome result (can finally use my NUCintosh without random freezes and reboots)

**Comment by alexpotter1** [comment] 2020-04-22 23:22
Hi dzoerb, thanks for the feedback!

> I can't get HDMI to work (don't have DP to test) but just having HDMI plugged in will start the boot process and at the stage where you would expect the Apple Logo the screen just turns black and the NUC reset itself

I just cloned fresh `master` onto a USB and unplugged DP to test with only HDMI (I usually run two displays, hence the need for LSPCON awareness) and was unfortunately unable to reproduce? The system booted into macOS seemingly okay (albeit with a momentary glitch just before the loading bar completed, but it resolved itself)

Which version of macOS are you running may I ask?

Since you mentioned you don't even get an Apple logo - I'm curious to know what BIOS version you're running? Maybe try updating if you haven't already 
https://downloadcenter.intel.com/product/89187/Intel-NUC-Kit-NUC6i7KYK

Also double check your BIOS settings in case there's anything funky there

If that's still a no-go maybe try playing around with the framebuffer settings, namely perhaps `enable-hdmi20` or `AAPL,GfxYTile`

> Just FYI - I have replaced VBoxHfs.efi with HfsPlus.efi so OpenCore can see and boot my APFS Fusion Drive. (I've got two exactly the same Crucial M2 SSD installed)

`ApfsDriverLoader.efi` should be the only UEFI driver responsible for loading APFS volumes (in fact, it chainloads the `apfs.efi` driver on the volume itself) - so `VBoxHfs.efi` and `HfsPlus.efi` in theory shouldn't make a difference as they refer to loading HFS+ volumes only

> Thanks a lot for your work, pretty straight forward process with awesome result (can finally use my NUCintosh without random freezes and reboots)

Thanks! There's still a few things here and there I'm trying to work on (namely sleep, RehabMan's NUC SSDT is included but that hasn't been updated since Sierra, so maybe that's involved...and Thunderbolt hotplug) but glad to know it's at least somewhat usable :)

**Comment by alexpotter1** [comment] 2020-04-22 23:26
c52e7d15 also rolled back a framebuffer patch forcing con1 to appear as HDMI - since that connector should be behind LSPCON anyway, the type probably shouldn't be being changed from DP

**Comment by ghost** [comment] 2020-04-23 19:23
Quick update - I'm running the latest BIOS (067) with Catalina 10.15.4. 
The BIOS is set to Optimized Defaults except that I have disabled VT-d, WIFI and the SD Card reader.
I've cloned the latest master and still no luck. However if I change the section PciRoot(0x0)/PCI(0x2,0x0) to the bare minimum and just keep the entries for AAPL,ig-platform-id, device-id and model I can boot via HDMI.
However I experince some drops/freezes now (seeing a lot of com.apple.displaypolicyd crashes in system.log...)
Would be great if we can work out the correct settings for the GPU to get the system more stable.
Also the latest master doesn't seem to auto-boot the MacHD in OpenCore? Always have a USB keyboard connected just to select the correct boot system :)

**Comment by ghost** [comment] 2020-04-24 08:12
Figured the issue was with 'framebuffer-con1-has-lspcon'. As soon as I removed that entry I can boot fine using HDMI. Still seeing the com.apple.displaypolicyd crashes though. Will monitor and let you know.

**Comment by alexpotter1** [comment] 2020-04-28 08:41
I've been changing some configuration related to the framebuffer/WhateverGreen over the last few days and found that LSPCON support doesn't seem as stable as I'd like it to be. It was initially enabled to be able to boot with dual monitors (without it, only HDMI would be recognised), but it appears to be the case that dual monitors continues to work (HDMI + mini-DP) without LSPCON with a WEG update.

a182e791 disables LSPCON and injects less framebuffer properties, hopefully for greater stability:

- `device-id` changed to HD 530 (iMac17,1)
- `disable-agdc` enabled (new in WEG 1.3.8)
- Removed explicit framebuffer connector pipe patches (since hotplug appears to work?)

Coincidentally, this also appears to (partially) fix a couple of issues that were remaining:

- Display hotplugging now works correctly (system would panic when doing this beforehand)
- Sleep partially works: Sleeps correctly, still wakes to black screen, but power cycling a monitor brings back the display (beforehand, system would panic shortly after wake)

I've also removed the explicit `agdpmod` boot-arg to let WEG automatically figure it out based on the connected display configuration.

> However I experince some drops/freezes now (seeing a lot of com.apple.displaypolicyd crashes in system.log...)

Haven't seen this yet locally but there's a chance this could be related to AppleGraphicsDeviceControl - removed `agdpmod` and AGDC (should?) be disabled by WEG now. Do you get this when Thunderbolt is connected?

> Also the latest master doesn't seem to auto-boot the MacHD in OpenCore? Always have a USB keyboard connected just to select the correct boot system :)

This is a known bug in OpenCanopy that should be fixed soon, given that it's fairly new. If you'd prefer to use the text-based boot screen, change Misc->Boot->PickerMode from `External` to `Builtin`.

**Comment by ghost** [comment] 2020-04-28 11:17
Thats's brilliant - I just rebooted with the updated master and it works like a charm. 
I have switched `PickerMode` to `Builtin` for now to get rid of the USB keyboard :)
Also the `com.apple.displaypolicyd` messages in `system.log` are now gone.
Thanks again for your help & the efforts you put in to it - really appreciate it!

**Closed as completed** 2020-04-28 12:27 UTC
